version: 2
updates:
  # Enable version updates for Nuget (Backend)
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "daily"

  # Enable version updates for Elm (Frontend)
  - package-ecosystem: "elm"
    directory: "/frontend"
    schedule:
      interval: "daily"

  # Enable version updates for Docker (Backend)
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"

  # Enable version updates for Docker (Frontend)
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
